name: workflow3
on:
  workflow_dispatch:
jobs:
  invoke_workflow:
    runs-on: ubuntu-latest
    steps:
    - name: some step ( print datetime )
      run: |
        date +"%F_%H-%m-%S"
        sleep 30 # Just easier for monitoring progress from github action page
        echo 'SOME STEP EXECUTED !'
# The End !
