name: workflow1
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    # Branch name ^^^ only in the file that should start on push
jobs:
  invoke_workflow:
    runs-on: ubuntu-latest
    steps:
    - name: some step ( print datetime )
      run: |
        date +"%F_%H-%m-%S"
        echo 'SOME STEP EXECUTED !'
    - name: Invoke workflow 2
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: workflow2
        #         ^^^^^^ should match name field in target workflow
        token: ${{ secrets.PERSONAL_TOKEN }}
    - name: Invoke workflow 3
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: workflow3
        #         ^^^^^^ should match name field in target workflow
        token: ${{ secrets.PERSONAL_TOKEN }}
# How to make secret personal token : 
# 1. https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
# 2. https://docs.github.com/en/actions/reference/authentication-in-a-workflow#using-the-github_token-in-a-workflow
